server:
  port: 9002
spring:
  application:
    name: customer-application
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka


ignite-client:
  addresses: 127.0.0.1:10800 # this is mandatory property!
  timeout: 10000
  tcpNoDelay: false
